<article id="page_page">
<?php echo $this->translate('DiscoverPHP.com is an open source project written in Zend Framework (PHP). Here you can get source files.'); ?>
<br /><br />
<?php echo $this->translate('Used version of Zend Framework'); ?>: <strong><?php echo Zend_Version::VERSION; ?></strong>
<br /><br />
<table id="source_table">
<tr>
<td>Git:</td>
<td>git@github.com:MariuszT/DiscoverPHP.com.git</td>
</tr>
<tr>
<td></td>
<td><a href="https://github.com/MariuszT/DiscoverPHP.com" target="_blank">https://github.com/MariuszT/DiscoverPHP.com</a></td>
</tr>
<tr>
<td>RAR:</td>
<td><a href="/source/latest.rar"><?php echo $this->translate('latest version'); ?></a></td>
</tr>
</table>
</article>